// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistencia.Data;

#nullable disable

namespace Persistencia.Migrations
{
    [DbContext(typeof(customDBContext))]
    [Migration("20261007133538_randomMigrate")]
    partial class randomMigrate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modelo.CusPersona", b =>
                {
                    b.Property<int>("Persona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Persona"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Domicilio")
                        .HasColumnType("text");

                    b.Property<short>("EmailValido")
                        .HasColumnType("smallint");

                    b.Property<string>("EstadoCivil")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<int?>("IdentidadGenero")
                        .HasColumnType("integer");

                    b.Property<string>("Localidad")
                        .HasColumnType("text");

                    b.Property<string>("MailInstitucional")
                        .HasColumnType("text");

                    b.Property<string>("MailPersonal")
                        .HasColumnType("text");

                    b.Property<string>("Nacionalidad")
                        .HasColumnType("text");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("NroDocumento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Provincia")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<char>("Sexo")
                        .HasColumnType("character(1)");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<short>("TipoDocumento")
                        .HasColumnType("smallint");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.HasKey("Persona");

                    b.ToTable("cus_persona", "negocio");
                });
#pragma warning restore 612, 618
        }
    }
}
